### ISSUE TITLE
LinkageError with 2024-09 staging release

### ISSUE THREAD

**Issue by ptziegler** [eclipse/ecf#116]
This is something that I noticed a few days ago, when trying to check out a project using [Oomph](https://github.com/eclipse-oomph/oomph).

Stack trace:
```
java.lang.LinkageError: loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6439794f wants to load class org.apache.hc.client5.http.impl.classic.HttpClientBuilder. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @2140dc2d. (org.apache.hc.client5.http.impl.classic.HttpClientBuilder is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2140dc2d, parent loader 'platform')
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient5.Activator.getHttpClientFactory(Activator.java:247)
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient5.Activator.registerHttpClient(Activator.java:290)
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient5.Activator.getRetrieveHttpClient(Activator.java:281)
	at org.eclipse.ecf.provider.filetransfer.httpclient5.HttpClientRetrieveFileTransferFactory.newInstance(HttpClientRetrieveFileTransferFactory.java:25)
	at org.eclipse.ecf.internal.provider.filetransfer.Activator.getFileTransfer(Activator.java:614)
	at org.eclipse.ecf.provider.filetransfer.retrieve.MultiProtocolRetrieveAdapter.sendRetrieveRequest(MultiProtocolRetrieveAdapter.java:94)
	at org.eclipse.oomph.setup.internal.core.util.ECFURIHandlerImpl$InputStreamConnectionHandler.sendConnectionRequest(ECFURIHandlerImpl.java:1943)
	at org.eclipse.oomph.setup.internal.core.util.ECFURIHandlerImpl$ConnectionHandler.process(ECFURIHandlerImpl.java:1642)
	at org.eclipse.oomph.setup.internal.core.util.ECFURIHandlerImpl.createInputStream(ECFURIHandlerImpl.java:321)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:358)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.handleArchiveRedirection(SetupCoreUtil.java:696)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.configureResourceSet(SetupCoreUtil.java:474)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.configureResourceSet(SetupCoreUtil.java:268)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.createResourceSet(SetupCoreUtil.java:262)
	at org.eclipse.oomph.setup.ui.recorder.RecorderManager.<clinit>(RecorderManager.java:121)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin.performStartup(SetupUIPlugin.java:218)
	at org.eclipse.oomph.setup.ui.EarlyStartup.earlyStartup(EarlyStartup.java:23)
	at org.eclipse.oomph.internal.ui.EarlyStart.run(EarlyStart.java:119)
	at org.eclipse.oomph.internal.ui.EarlyStart$1.run(EarlyStart.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

To reproduce, use the Oomph installer and set "Staging (2024-09) as product version.
![image](https://github.com/eclipse/ecf/assets/70652978/7f23115d-d31f-449b-9870-9db94507302b)

The setup fails halfway through, with the error mentioned above.
![image](https://github.com/eclipse/ecf/assets/70652978/7d20c865-9cdc-4b60-aaa1-3e275ee3616c)

The error doesn't show up with the 2024-06 release, so something must have changed between those releases that's causing this issue. Perhaps a different project also migrated to the HttpClient5, causing the classes to be loaded somewhere else?

**Comment by scottslewis** [comment]
@merks any ideas what's going on here?

**Comment by ptziegler** [comment]
Some additional information from my side, as I've just tested it on two other machines:

The problem seems to be exclusive to Windows 11 as I haven't been able to reproduce this on Linux. Very weird...

**Comment by merks** [comment]
II notice there are two versions of this library:

![image](https://github.com/eclipse/ecf/assets/208716/c281fd91-0bf7-4b55-a6eb-b1f4d7a57bfe)

I also notice that if I remove mpc there is only one version:

![image](https://github.com/eclipse/ecf/assets/208716/1c86d7aa-7b89-413e-8e86-0cfdf5852b4a)

And in that case there is no linkage exception.

But I find the content of the ECF release strange:

![image](https://github.com/eclipse/ecf/assets/208716/894cf2bd-3a4f-4108-906f-aacf430af036)

Somehow the ECF release don't just contain content from the most recent Orbit release as I would have expected:

![image](https://github.com/eclipse/ecf/assets/208716/b3d59180-d12f-48c8-ae67-cbcd8ebf05ea)

Looks like that needs to be revisited again too.  😢 

In any case, it appears that MPC's use of an older library version is the cause of the problem or more certainly is contributing to the problem.

**Comment by merks** [comment]
My guess would be that because the target platform uses the 4.32 repository which has older ECF content that older ECF dependencies can creep in:

![image](https://github.com/eclipse/ecf/assets/208716/b1e239e4-762b-4e15-a1d2-531c8d1b93e0)

**Comment by merks** [comment]
@ptziegler @scottslewis 

Thanks for reporting this problem and for bringing this to my attention!  💟 

I hope that we can nip this problem in the bud before M1 roles out the door and that MPC can roll out these changes as soon as possible:

https://github.com/eclipse-mpc/epp.mpc/pull/11

**Comment by scottslewis** [comment]
@merks two questions:

1) Is there anything else for ECF to do wrt this issue?
2) Should this issue remain open or be closed?

**Comment by merks** [comment]
There is nothing for ECF to do for this issue.  I think it should be closed.

I have the following PR to update ECFs dependencies properly:

https://github.com/eclipse/ecf/issues/116#issuecomment-2214990108

A snapshot build for that would be awesome...

**Comment by scottslewis** [comment]
> There is nothing for ECF to do for this issue. I think it should be closed.
> 
> I have the following PR to update ECFs dependencies properly:
> 
> [#116 (comment)](https://github.com/eclipse/ecf/issues/116#issuecomment-2214990108)
> 
> A snapshot build for that would be awesome...

I will produce one today.  Our ci instance seems very slow to respond today (ui), however:

https://ci.eclipse.org/ecf/

@merks do you know if this is a widespread problem...or just with our ci instance?

**Comment by merks** [comment]
The problems with ci instances seem widespread to me.  Some instances are fine while others are slow and fail for strange reasons.   I've had no end of problems for the last days...

**Comment by scottslewis** [comment]
> The problems with ci instances seem widespread to me. Some instances are fine while others are slow and fail for strange reasons. I've had no end of problems for the last days...

@merks:   Please color our instance (link above) in the latter category.  Our build typically takes less than 15 minutes total and it's not accepting any new jobs at all (pending state for last couple of hours).   Until this instance accepts and processes new jobs I can't produce a snapshot.

**Comment by merks** [comment]
When in doubt, create an issue:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4800

The good news is that with MPC's M1 contribution, the linkage problem is fixed.

**Comment by scottslewis** [comment]
Hi @merks 

Good news:  Our ci instance is running ok now
Bad news:  The build is failing with some problem I can't figure out.

Here's the failed run

https://ci.eclipse.org/ecf/job/ecf-github.master/112/

From the console output, it seems that this is the reason for failure...i.e. a dependency on jakarta.servlet that isn't in target platform?

Thanksinadvance.

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.7:assemble-repository (default-assemble-repository) on project org.eclipse.ecf.releng.repository: Cannot resolve dependencies of project org.eclipse.ecf:org.eclipse.ecf.releng.repository:eclipse-repository:3.15.2-SNAPSHOT
[ERROR] with context {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86_64, org.eclipse.update.install.sources=true}
[ERROR] Software being installed: org.eclipse.ecf.releng.repository raw:3.15.2.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):3.15.2-SNAPSHOT
[ERROR] Missing requirement: org.eclipse.ecf.remoteservice.servlet.feature.feature.group 1.0.400.v20240502-2212 requires 'org.eclipse.equinox.p2.iu; jakarta.servlet-api [6.0.0,6.0.0]' but it could not be found
[ERROR] Cannot satisfy dependency: org.eclipse.ecf.releng.repository raw:3.15.2.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):3.15.2-SNAPSHOT depends on: org.eclipse.equinox.p2.iu; org.eclipse.ecf.remoteservice.sdk.feature.feature.group 0.0.0
[ERROR] Cannot satisfy dependency: org.eclipse.ecf.remoteservice.sdk.feature.feature.group 3.15.2.v20240709-1538 depends on: org.eclipse.equinox.p2.iu; org.eclipse.ecf.remoteservice.servlet.feature.feature.group [1.0.400.v20240502-2212,1.0.400.v20240502-2212]: See log for details
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.7:assemble-repository (default-assemble-repository) on project org.eclipse.ecf.releng.repository: Cannot resolve dependencies of project org.eclipse.ecf:org.eclipse.ecf.releng.repository:eclipse-repository:3.15.2-SNAPSHOT
 with context {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86_64, org.eclipse.update.install.sources=true}
  Software being installed: org.eclipse.ecf.releng.repository raw:3.15.2.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):3.15.2-SNAPSHOT
  Missing requirement: org.eclipse.ecf.remoteservice.servlet.feature.feature.group 1.0.400.v20240502-2212 requires 'org.eclipse.equinox.p2.iu; jakarta.servlet-api [6.0.0,6.0.0]' but it could not be found
  Cannot satisfy dependency: org.eclipse.ecf.releng.repository raw:3.15.2.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):3.15.2-SNAPSHOT depends on: org.eclipse.equinox.p2.iu; org.eclipse.ecf.remoteservice.sdk.feature.feature.group 0.0.0
  Cannot satisfy dependency: org.eclipse.ecf.remoteservice.sdk.feature.feature.group 3.15.2.v20240709-1538 depends on: org.eclipse.equinox.p2.iu; org.eclipse.ecf.remoteservice.servlet.feature.feature.group [1.0.400.v20240502-2212,1.0.400.v20240502-2212]
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main (Maven35Launcher.java:138)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at jenkins.maven3.agent.Maven35Main.launch (Maven35Main.java:179)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:140)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:71)
    at hudson.remoting.UserRequest.perform (UserRequest.java:211)
    at hudson.remoting.UserRequest.perform (UserRequest.java:54)
    at hudson.remoting.Request$2.run (Request.java:377)
    at hudson.remoting.InterceptingExecutorService.lambda$wrap$0 (InterceptingExecutorService.java:78)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833)
Caused by: org.apache.maven.plugin.MojoFailureException: Cannot resolve dependencies of project org.eclipse.ecf:org.eclipse.ecf.releng.repository:eclipse-repository:3.15.2-SNAPSHOT
 with context {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86_64, org.eclipse.update.install.sources=true}
  Software being installed: org.eclipse.ecf.releng.repository raw:3.15.2.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):3.15.2-SNAPSHOT
  Missing requirement: org.eclipse.ecf.remoteservice.servlet.feature.feature.group 1.0.400.v20240502-2212 requires 'org.eclipse.equinox.p2.iu; jakarta.servlet-api [6.0.0,6.0.0]' but it could not be found
  Cannot satisfy dependency: org.eclipse.ecf.releng.repository raw:3.15.2.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):3.15.2-SNAPSHOT depends on: org.eclipse.equinox.p2.iu; org.eclipse.ecf.remoteservice.sdk.feature.feature.group 0.0.0
  Cannot satisfy dependency: org.eclipse.ecf.remoteservice.sdk.feature.feature.group 3.15.2.v20240709-1538 depends on: org.eclipse.equinox.p2.iu; org.eclipse.ecf.remoteservice.servlet.feature.feature.group [1.0.400.v20240502-2212,1.0.400.v20240502-2212]
    at org.eclipse.tycho.p2tools.RepositoryReferenceTool.addTargetPlatformRepository (RepositoryReferenceTool.java:165)
    at org.eclipse.tycho.p2tools.RepositoryReferenceTool.getVisibleRepositories (RepositoryReferenceTool.java:108)
    at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.execute (AssembleRepositoryMojo.java:336)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main (Maven35Launcher.java:138)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at jenkins.maven3.agent.Maven35Main.launch (Maven35Main.java:179)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:140)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:71)
    at hudson.remoting.UserRequest.perform (UserRequest.java:211)
    at hudson.remoting.UserRequest.perform (UserRequest.java:54)
    at hudson.remoting.Request$2.run (Request.java:377)
    at hudson.remoting.InterceptingExecutorService.lambda$wrap$0 (InterceptingExecutorService.java:78)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833)
Caused by: org.eclipse.tycho.p2.resolver.ResolverException: See log for details
    at org.eclipse.tycho.p2resolver.ProjectorResolutionStrategy.resolve (ProjectorResolutionStrategy.java:119)
    at org.eclipse.tycho.p2resolver.AbstractResolutionStrategy.resolve (AbstractResolutionStrategy.java:55)
    at org.eclipse.tycho.p2resolver.P2ResolverImpl.resolveDependencies (P2ResolverImpl.java:231)
    at org.eclipse.tycho.p2resolver.P2ResolverImpl.resolveTargetDependencies (P2ResolverImpl.java:124)
    at org.eclipse.tycho.p2resolver.P2DependencyResolver.doResolveDependencies (P2DependencyResolver.java:378)
    at org.eclipse.tycho.p2resolver.P2DependencyResolver.resolveDependencies (P2DependencyResolver.java:328)
    at org.eclipse.tycho.p2tools.RepositoryReferenceTool.addTargetPlatformRepository (RepositoryReferenceTool.java:133)
    at org.eclipse.tycho.p2tools.RepositoryReferenceTool.getVisibleRepositories (RepositoryReferenceTool.java:108)
    at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.execute (AssembleRepositoryMojo.java:336)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main (Maven35Launcher.java:138)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at jenkins.maven3.agent.Maven35Main.launch (Maven35Main.java:179)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:140)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:71)
    at hudson.remoting.UserRequest.perform (UserRequest.java:211)
    at hudson.remoting.UserRequest.perform (UserRequest.java:54)
    at hudson.remoting.Request$2.run (Request.java:377)
    at hudson.remoting.InterceptingExecutorService.lambda$wrap$0 (InterceptingExecutorService.java:78)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833)

**Comment by merks** [comment]
I did successfully run the build locally. I’ll have a look tomorrow during the day.

**Comment by merks** [comment]
It's an odd problem.  The target platform in the IDE shows this content:

![image](https://github.com/eclipse/ecf/assets/208716/22881e02-a1b9-4499-91fa-adadbe70b543)

The local build uses that version:

![image](https://github.com/eclipse/ecf/assets/208716/5ee8de5c-4ee4-48df-b539-ede15cc9923a)

But the error message is about 6.0.0:

```
org.eclipse.ecf.remoteservice.servlet.feature.feature.group 1.0.400.v20240502-2212 requires 'org.eclipse.equinox.p2.iu; jakarta.servlet-api [6.0.0,6.0.0]'
```

But I look at what's build, and that's different from the above error

![image](https://github.com/eclipse/ecf/assets/208716/bad23892-ce1d-4087-ac0e-57a7c09bad44)

So as I write this, it screams out, this is an API baseline replacement problem.

**Comment by scottslewis** [comment]
Thanks @merks .

Here is the 3.15.2 snapshot build

https://download.eclipse.org/rt/ecf/snapshot/

**Comment by merks** [comment]
Thanks. I've updated SimRel:

https://github.com/eclipse-simrel/simrel.build/pull/461

And the platform is in the works:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2183
