### ISSUE TITLE
LinkageError when multiple versions of org.apache.hc.client5.http.impl.classic.HttpClientBuilder are available

### ISSUE THREAD

**Issue by scottkurz** [eclipse/ecf#132]
This seems to have at least a bit of overlap with https://github.com/eclipse/ecf/issues/116 though I didn't try to make sense of how the resolution there might apply here. 

Let me just write this up.

## Stack trace
Upon trying to install a new Eclipse Marketplace entry, I get: 

```
!ENTRY org.eclipse.ecf.provider.filetransfer.httpclient5 4 0 2024-09-23 14:58:29.922
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.ServiceException: Exception in org.apache.felix.scr.impl.manager.SingleComponentManager.getService()
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:236)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:118)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:580)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:548)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:672)
	at org.osgi.util.tracker.ServiceTracker.addingService(ServiceTracker.java:419)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:947)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:257)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:184)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:324)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:267)
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient5.Activator.getHttpClientFactory(Activator.java:243)
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient5.Activator.registerHttpClient(Activator.java:290)
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient5.Activator.getRetrieveHttpClient(Activator.java:281)
	at org.eclipse.ecf.provider.filetransfer.httpclient5.HttpClientRetrieveFileTransferFactory.newInstance(HttpClientRetrieveFileTransferFactory.java:25)
	at org.eclipse.ecf.internal.provider.filetransfer.Activator.getFileTransfer(Activator.java:614)
	at org.eclipse.ecf.provider.filetransfer.retrieve.MultiProtocolRetrieveAdapter.sendRetrieveRequest(MultiProtocolRetrieveAdapter.java:94)
	at org.eclipse.oomph.setup.internal.core.util.ECFURIHandlerImpl$InputStreamConnectionHandler.sendConnectionRequest(ECFURIHandlerImpl.java:1943)
	at org.eclipse.oomph.setup.internal.core.util.ECFURIHandlerImpl$ConnectionHandler.process(ECFURIHandlerImpl.java:1642)
	at org.eclipse.oomph.setup.internal.core.util.ECFURIHandlerImpl.createInputStream(ECFURIHandlerImpl.java:321)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:358)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.handleArchiveRedirection(SetupCoreUtil.java:696)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.configureResourceSet(SetupCoreUtil.java:474)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.configureResourceSet(SetupCoreUtil.java:268)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.createResourceSet(SetupCoreUtil.java:262)
	at org.eclipse.oomph.setup.ui.recorder.RecorderManager.<clinit>(RecorderManager.java:121)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin.performStartup(SetupUIPlugin.java:218)
	at org.eclipse.oomph.setup.ui.EarlyStartup.earlyStartup(EarlyStartup.java:23)
	at org.eclipse.oomph.internal.ui.EarlyStart.run(EarlyStart.java:119)
	at org.eclipse.oomph.internal.ui.EarlyStart$1.run(EarlyStart.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.LinkageError: loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @4c7e652c wants to load class org.apache.hc.client5.http.impl.classic.HttpClientBuilder. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @196747aa. (org.apache.hc.client5.http.impl.classic.HttpClientBuilder is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @196747aa, parent loader 'platform')
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3621)
	at java.base/java.lang.Class.getConstructors(Class.java:2286)
	at org.apache.felix.scr.impl.inject.internal.ComponentConstructorImpl.<init>(ComponentConstructorImpl.java:98)
	at org.apache.felix.scr.impl.inject.internal.ComponentMethodsImpl.initComponentMethods(ComponentMethodsImpl.java:110)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.initDependencyManagers(AbstractComponentManager.java:1029)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1057)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:920)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:226)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:223)
	... 33 more
```

### Env
* Windows 11 (hasn't been recreated on Mac)
* Java 23 (the default from the installer setup)

### Steps
1. Install 2024-06 Eclipse, "Enterprise Java" package
2. Install IBM Liberty Developer Tools:  https://marketplace.eclipse.org/content/ibm-liberty-developer-tools
3.  **(EDIT 9/23 - The version recreating this problem has NOT yet made it to Eclipse Marketplace.  This instruction will apply shortly but not quite yet.  Sorry about this, I realized this after writing this up, I was testing with a still-unpublished binary.)**
Install Liberty Tools:  https://marketplace.eclipse.org/content/liberty-tools

The step 3. will fail and show a message which maps to this entry in the workspace log:

>  !MESSAGE Missing requirement: Liberty Tools Support for Language Servers 24.0.9.202409170137 (io.openliberty.tools.eclipse.lsp4e 24.0.9.202409170137) requires 'osgi.bundle; org.eclipse.lsp4mp.jdt.core 0.0.0' but it could not be found

Before this error message in the log, there are errors like the stack trace above.   I believe the problem is that the ECF component cannot go and download this org.eclipse.lsp4mp.jdt.core install dependency because of problems having two versions of the `org.apache.hc.client5.*` packages available. 

### Observations

After step 2, if I go into the Host OSGi console and do:
> g! packages org.apache.hc.client5.http

I see both a 5.2.1 and a 5.3.1 version of the `org.apache.httpcomponents.client5.httpclient5` bundle:

>bundle-version:Version="5.2.1.v20230802-0806"; version:Version="5.2.1"; 
>bundle-version:Version="5.3.1.v20240126-0900"; version:Version="5.3.1"; 

Looking at the error message, I guessed that somehow the two were conflicting.  So, to try to workaround, after steps 1, 2 above in the recreate, I deleted the `org.apache.httpcomponents.client5.httpclient5_5.3.1.v20240126-0900.jar` bundle from my plugins pool, and then restarted with `-clean`.  When I did this, I was able to complete step 3. 

This seems to me evidence that this is a bundle coexistence problem.  

I don't have any insight into why step 2. drags in version 5.3.1 of this bundle when version 5.2.1 is already installed (there is a good amount of stuff getting installed here in step 2.).

**Comment by scottslewis** [comment]
This appears to me to be the same problem as in #116.   Would you be able to try an Eclipse version since #116 was fixed?  e.g. 2024-09?

**Comment by scottkurz** [comment]
> This appears to me to be the same problem as in #116. Would you be able to try an Eclipse version since #116 was fixed? e.g. 2024-09?

OK, yes, it seems to be fixed. I only see httpclient5 v5.3.1 now.    Yeah, it did seem similar to me but I thought since that issue didn't mention 2024-06 that it needed a separate look.   I'll close though, thank you.
