### ISSUE TITLE
Weird "Address already in use" problem after upgrading ECF version

### ISSUE THREAD

**Issue by phermsdorf** [eclipse/ecf#23]
Hi,

with a new release we updated ECF from 3.14.18 (2020-12) to 3.14.33 (2022-06) (i'm referring to the version of the org.eclipse.ecf.remoteservice.sdk feature).
In our setup we use the ecf.generic server to connect RCP clients via ecf.generic provider to one application server and calling remote services from that server.

In some setup's we now encounter the problem that remote services on the client side come and go after a few seconds (with IMPORT_UNREGISTRATION events). 
On server side there are no errros in the logs but when stopping the server the following messages appear in the log:

```
2023-01-25 10:49:36,051 [Equinox Log Thread - Equinox Container: 6061ab58-28a6-4425-bb0b-6a7c526239c6] ERRORorg.osgi.framework - org.eclipse.core.runtime.Status[plugin=org.eclipse.ecf.provider;code=4441;message=createInstance;severity4;exception=java.net.BindException: Address already in use: NET_Bind;children=[]]
java.net.BindException: Address already in use: NET_Bind
    at java.base/java.net.PlainSocketImpl.bind0(Native Method)
    at java.base/java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:132)
    at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
    at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
    at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
    at org.eclipse.ecf.provider.comm.tcp.Server.<init>(Server.java:50)
    at org.eclipse.ecf.provider.generic.TCPServerSOContainerGroup.putOnTheAir(TCPServerSOContainerGroup.java:82)
    at org.eclipse.ecf.provider.generic.TCPServerSOContainer.<init>(TCPServerSOContainer.java:107)
    at org.eclipse.ecf.provider.generic.GenericContainerInstantiator.createServerContainer(GenericContainerInstantiator.java:306)
    at org.eclipse.ecf.provider.generic.GenericContainerInstantiator.createInstance(GenericContainerInstantiator.java:321)
    at org.eclipse.ecf.core.ContainerFactory.createContainer(ContainerFactory.java:298)
    at org.eclipse.ecf.core.ContainerFactory.createContainer(ContainerFactory.java:594)
    at org.eclipse.ecf.osgi.services.remoteserviceadmin.AbstractContainerSelector.createContainer(AbstractContainerSelector.java:175)
    at com.godyo.p5.server.internal.AuthHostContainerSelector.createContainer(AuthHostContainerSelector.java:35)
    at org.eclipse.ecf.osgi.services.remoteserviceadmin.AbstractHostContainerSelector.createRSContainer(AbstractHostContainerSelector.java:461)
    at org.eclipse.ecf.osgi.services.remoteserviceadmin.AbstractHostContainerSelector.createMatchingContainer(AbstractHostContainerSelector.java:425)
    at org.eclipse.ecf.osgi.services.remoteserviceadmin.AbstractHostContainerSelector.createAndConfigureHostContainers(AbstractHostContainerSelector.java:333)
    at org.eclipse.ecf.osgi.services.remoteserviceadmin.HostContainerSelector.selectHostContainers(HostContainerSelector.java:80)
    at org.eclipse.ecf.osgi.services.remoteserviceadmin.RemoteServiceAdmin$1.run(RemoteServiceAdmin.java:311)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.ecf.osgi.services.remoteserviceadmin.RemoteServiceAdmin.exportService(RemoteServiceAdmin.java:309)
    at org.eclipse.ecf.osgi.services.remoteserviceadmin.AbstractTopologyManager.handleServiceRegistering(AbstractTopologyManager.java:487)
    at org.eclipse.ecf.osgi.services.remoteserviceadmin.TopologyManagerImpl$1.run(TopologyManagerImpl.java:386)
    at java.base/java.lang.Thread.run(Thread.java:834)
2023-01-25 10:49:36,067 [Equinox Log Thread - Equinox Container: 6061ab58-28a6-4425-bb0b-6a7c526239c6] WARN org.osgi.framework - org.eclipse.core.runtime.Status[plugin=org.eclipse.ecf.osgi.services.remoteserviceadmin;code=2;message=org.eclipse.ecf.osgi.services.remoteserviceadmin.EndpointDescription:verifyECFProperties:ECFEndpointDescription property ecf.endpoint.ts not set.  Using OSGI endpoint.service.id;severity2;exception=null;children=[]]
2023-01-25 10:49:36,067 [Start Level: Equinox Container: 6061ab58-28a6-4425-bb0b-6a7c526239c6] WARN o.e.j.o.b.JettyBootstrapActivator - OSGi support for java.util.ServiceLoader may not be present. You may experience runtime errors.
2023-01-25 10:49:36,067 [Equinox Log Thread - Equinox Container: 6061ab58-28a6-4425-bb0b-6a7c526239c6] ERRORorg.osgi.framework - org.eclipse.core.runtime.Status[plugin=org.eclipse.ecf.osgi.services.remoteserviceadmin;code=4;message=org.eclipse.ecf.osgi.services.remoteserviceadmin.TopologyManagerImpl:handleRemoteAdminEvent.EXPORT_ERROR:Export error with event=RemoteServiceAdminEvent[containerID=null, getType()=6, getSource()=org.eclipse.ecf.osgi.services.remoteserviceadmin_4.9.3.v20220116-0708 [192], getException()=org.eclipse.ecf.core.ContainerCreateException: Create of containerType=ecf.generic.server failed., getImportReference()=null, getExportReference()=null];severity4;exception=null;children=[]]
2023-01-25 10:49:36,176 [Equinox Log Thread - Equinox Container: 6061ab58-28a6-4425-bb0b-6a7c526239c6] ERRORorg.osgi.framework - org.eclipse.core.runtime.Status[plugin=org.eclipse.ecf.provider;code=4441;message=createInstance;severity4;exception=java.net.BindException: Address already in use: NET_Bind;children=[]]
java.net.BindException: Address already in use: NET_Bind
    at java.base/java.net.PlainSocketImpl.bind0(Native Method)
    at java.base/java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:132)
 ... 
```
We triple checked that no other services are running on that port using netstat. When the server is started netstat shows a binding of that java process on that specific port.

Operating System (different Windows Server OS) and Java 11 version were not changed.
We currently try to move the server to a Linux instance to see if that changes something.

An update to the latest ECF release is currently not possible because RCP dependency changes regarding jetty 10/servlet versions/javax namespace things.

Any ideas what could cause that issue and how to fix that?

Thanks!
Bye Peter

**Comment by scottslewis** [comment]
> Hi,
> 
> with a new release we updated ECF from 3.14.18 (2020-12) to 3.14.33 (2022-06) (i'm referring to the version of the org.eclipse.ecf.remoteservice.sdk feature). In our setup we use the ecf.generic server to connect RCP clients via ecf.generic provider to one application server and calling remote services from that server.
> 
> In some setup's we now encounter the problem that remote services on the client side come and go after a few seconds (with IMPORT_UNREGISTRATION events). 

Has this (unsolicited IMPORT_UNREGISTRATION) been happening previously, or is it new?   

What you describe after this seems to me most likely some sort of weird dynamics associated with how clients discover and initiate connection with the server.

Do you have any information on what the client (and server-side) context is where you get these UNREGISTRATION events on the client?   Can you reproduce it with a single client?    What do clients do when they receive an IMPORT_UNREGISTRATION? 

Also:  what are you doing for the clients to discover and connect to the server?

There have not been large changes in the ecf.generic provider recently...and I've not ever seen anything like this in testing.   You say that the Address already in use message come when shutting the server *down*?   That's really confusing as you can see the Address already in use exception happens because the service is being *exported*.   I can't understand why any service would be exported as part of the server shutdown process.

**Comment by phermsdorf** [comment]
Thanks for your comments @scottslewis .

Actually your comments put me (at least for the "Address already in use") error in the right direction:

For this released we changed the way our application is stopped. Until now the application process just got killed (we use apache commons daemon for service management in windows). This leads to several problem because all kind of resources are not properly cleaned up and closed.
Now we used an approach i saw in apache karaf. To stop our service we launch the process again with a stop command line argument which then connects to a opened socket of the already running process and sends a stop command which then causes an exit in IApplication.start of the running service.

The problem here is that the IApplication.start which checks for the stop command line argument gets called after TopologyManagerImpl.exportRegisteredServices (at keast in the build product, not in the IDE) which try's to start the remote services which then of course leads to that exception.

So thanks for your pointers. I will close this issue.

The problem with the coming and going services is still there. I need to investigate further and will open another issue if i find something.

Bye Peter

**Comment by scottslewis** [comment]
Hi Peter.  Thanks for the explanation.   Since you are using Karaf does your use case fit:   dev:restart command via console (or remote console)?

https://karaf.apache.org/manual/latest-2.x/users-guide/start-stop.html

**Comment by phermsdorf** [comment]
Hi Scott. I've used karaf in another project and just looked how they do graceful shutdown when running as windows service. 
We still use equinox as runtime of the server because we can build and deploy as product in the same way as our RCP.
