### ISSUE TITLE
TLSv1.3 not supported in Eclipse ECF

### ISSUE THREAD

**Issue by mdaloia** [eclipse/ecf#26]
Maybe I'm wrong or overlooking something, but based on this [SSLContextHelper code](https://github.com/eclipse/ecf/blob/696f197b4131f84c416135cd6117384567b0da56/framework/bundles/org.eclipse.ecf.ssl/src/org/eclipse/ecf/internal/ssl/SSLContextHelper.java#L32-L36) and a test I've made there is no support to TLSv1.3.

Am I right?

The test that I've made was with the following setup:
- Tried nginx and Apache HTTPD Docker images
- Configured to support only TLSv1.3
- Configured with a certificate and its private key
- Added the root certificate into the `cacerts` file of the JVM running Eclipse
- Configured to serve a p2 repository
- Added the custom domain (`end-user.foo.bar` in this example) to the hosts file (`/etc/hosts`)

If from a browser I access to https://end-user.foo.bar:8443/artifacts.xml.xz it can be downloaded. 
I've also put an `index.html` and it is served ok without any issue or certificate warning.

But when I add the URL of this p2 repository in the `Available Software Sites` and hit the `Reload` button I get this exception:

```
org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at https://end-user.foo.bar:8443/artifacts.xml.
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:249)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepositoryFactory.getLocalFile(SimpleArtifactRepositoryFactory.java:68)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepositoryFactory.load(SimpleArtifactRepositoryFactory.java:92)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepositoryFactory.load(SimpleArtifactRepositoryFactory.java:80)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.factoryLoad(ArtifactRepositoryManager.java:92)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:787)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:685)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.basicRefreshRepository(AbstractRepositoryManager.java:205)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.refreshRepository(ArtifactRepositoryManager.java:136)
	at org.eclipse.equinox.p2.ui.RepositoryManipulationPage.lambda$17(RepositoryManipulationPage.java:596)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:340)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:186)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:273)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:241)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:148)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at org.eclipse.ecf.provider.filetransfer.httpclient5.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:251)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Downgrading the server to TLSv1.2 works without any issue inside Eclipse.

**Comment by scottslewis** [comment]
Hi @mdaloia 

Thanks for the report.  Just to explain:  It's been a while since this SSLContext code has been touched, and I don't think TLSv1.3 was available at the time.

Also:  ECF has a provider architecture for http/https communication/file transfer.   Currently with Eclipse it is using the apache5 client...as per this from your stack trace:

 org.apache.hc.client5.http.ssl

But there are actually several providers that have their own impl of the SSLContextHelper.

I've just updated all of them to add TLSv1.3 to the set of protocols supported by the jvm.  Note that TLSv1.3 is only supported in java 8 (8u261 b12 or greater)

Here's the pull request

https://github.com/eclipse/ecf/pull/28

Please let me know if you see any problem with the pr.  All I did was add TLSv1.3 to the jreProtocols list in the 3 relevant providers 1) in org.eclipse.ecf.ssl, 2) httpclient5 provider; 3) httpclientjava provider.

I would appreciate it if you were to test this build in your environment.   Probably easiest if you install into eclipse via p2 repo of ECF version 3.14.38 which will be available here:

https://download.eclipse.org/rt/ecf/snapshot/

The repo is in https://download.eclipse.org/rt/ecf/snapshot/site.p2

Note also that with this fix you should be able to *force* the client to use TLSv1.3 (or lower version) by setting a system property:

-Dhttps.protocol=TLSv1.3

**Comment by mdaloia** [comment]
@scottslewis Thanks for the changes! Sure I will test it once the version is available in the p2 repo... currently I see that the latest one published is 3.14.37.

<img width="909" alt="image" src="https://user-images.githubusercontent.com/1738654/227682487-d3d78975-2585-4813-96f4-5f7c58143acf.png">

Regarding the PR, I think the changes are ok. I hope that it would be enough. Will see :)

**Comment by scottslewis** [comment]
Hi @mdaloia

>that the latest one published is 3.14.37.

Yes that's true...sorry about that.  I had a problem with our builder..which is visible to you

https://ci.eclipse.org/ecf/job/ecf-github.master/

You can see that builds 29 and 30 (3.14.28) failed...well they are failing with an error that I don't understand, so I've communicated the issue to the eclipse foundation build masters so that I can diagnose and fix.

Once I get the builder fixed it will produce 3.14.38 snapshot.  In the mean time, you can see the changes in source here https://github.com/eclipse/ecf/commit/dbcee46d3f33f5e9f00b7510b1a0814012dba53a

And in the mean time, if you wish you can get the latest (master HEAD now) and work with it/test it in your Eclipse environment from the ECF repo at:  https://github.com/eclipse/ecf  

If you want/need any help with anything any of that please let me know here.  I will let you know when the builder is back doing it's job and 3.14.38 is available.

**Comment by scottslewis** [comment]
Hi.   I got the builder fixed, so a snapshot version of 3.14.38 (with the fix for this issue) is available here

https://download.eclipse.org/rt/ecf/snapshot/

The p2 repo is here:  https://download.eclipse.org/rt/ecf/snapshot/site.p2

Please test this build in your environment for added TLSv1.3 support and let me know here.

**Comment by mdaloia** [comment]
@scottslewis 

I've tested it and seems to be working. Thanks!

For reference this is what I did:
1. Download Eclipse SDK 4.27 from https://download.eclipse.org/eclipse/downloads/drops4/R-4.27-202303020300/#EclipseSDK
    _(with the Eclipse Java package something is caching the result of first good Reload and it doesn't fails when the `protocol_version` error is thrown so it is not useful for testing purposes... I suspect of Oomph)._ 
2. Configured it with a JVM with that had in `cacerts` file my custom Root CA used by the cert on my local nginx serving a p2 site over TLSv1.3
3. I've added this under `-vmargs` of the `eclipse.ini` file: `-Dhttps.protocols=TLSv1.3,TLSv1.2`
4. Started Eclipse and added my TLSv1.3 p2 site
5. Hit Reload ==> Error due to: `javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version`
6. Added the ECF Snapshots p2 site and hit Reload
7. Checked for updates (oddly enough it said that there weren't updates available)
8. I went to `Install new software...`
9. Selected the ECF update site and the following plugins/features to install:
    ```
    ECF Apache Httpclient 5 FileTransfer Provider	1.1.701.v20230324-2346
    ECF Core SSL Feature	1.1.501.v20230324-2349
    ECF Java/JVM 11+ HttpClient FileTransfer Provider	1.0.0.v20230324-2346
    ```
    (Fun fact: after hitting `Next >` it said that they will be updated because they were already installed 🤷🏻‍♂️ )
10. Restarted Eclipse
11. I went to `Available Software Sites` preferences
12. Selected my p2 Update Site and hit Reload
13. It read successfully the p2 metadata! 🎉 

I also checked the TLS handshake using `-Djavax.net.debug=all` just to be sure that it was using `TLSv1.3`.
- The ServerHello handshake message said `"selected version": [TLSv1.3]`, and also
   ```
   javax.net.ssl|DEBUG|46|HttpClient-1-Worker-0|2023-04-09 19:27:48.611 ART|ServerHello.java:963|Negotiated protocol version: TLSv1.3
   ```
------

One thing that I couldn't figure it out is that in some cases it works (i.e. it ends up using TLSv1.3) even without the patch:
- before applying the patch and without configuring the `-Dhttps.protocols` at all ==> **WORKS**
- before applying the patch and configuring `-Dhttps.protocols=TLSv1.3` ==> **WORKS**
- before applying the patch and configuring `-Dhttps.protocols=TLSv1.3,TLSv1.2` ==> **FAILS**
- before applying the patch and configuring `-Dhttps.protocols=TLSv1.2,TLSv1.3` ==> **FAILS**
- applying the patch and configuring `-Dhttps.protocols=TLSv1.3,TLSv1.2` ==> **WORKS**

Looking at the logs generated (using `-Djavax.net.debug=all`) in those cases the only thing that I found is that when it doesn't work the Ciphers Suites supported by TLSv1.3 (See [Java list](https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html#jsse-cipher-suite-names) and [RFC 8446](https://www.rfc-editor.org/rfc/rfc8446#appendix-B.4)) were being ignored...:
```
javax.net.ssl|ALL|22|Worker-2: https://server.local:8443/p2.index|2023-04-09 16:14:02.234 ART|SSLContextImpl.java:411|Ignore unsupported cipher suite: TLS_AES_256_GCM_SHA384
javax.net.ssl|ALL|22|Worker-2: https://server.local:8443/p2.index|2023-04-09 16:14:02.234 ART|SSLContextImpl.java:411|Ignore unsupported cipher suite: TLS_AES_128_GCM_SHA256
javax.net.ssl|ALL|22|Worker-2: https://server.local:8443/p2.index|2023-04-09 16:14:02.234 ART|SSLContextImpl.java:411|Ignore unsupported cipher suite: TLS_CHACHA20_POLY1305_SHA256
[...]
javax.net.ssl|DEBUG|22|Worker-2: https://server.local:8443/p2.index|2023-04-09 16:14:02.265 ART|HandshakeContext.java:303|No available cipher suite for TLSv1.3
```
... and thus TLSv1.3 couldn't be used. It tried to negotiate TLSv1.2 but as my test server is explicitly configured to support only TLSv1.3 it ends with the `protocol_version` failure.

**Comment by scottslewis** [comment]
Thanks @mdaloia for reporting this and testing the fix.  

I suspect that the reason for the https.protocols=TLSv1.3 working before patch is the way the original code is working and/or the version of the jdk being used to run eclipse underneath.  

I think it's going to meet needs enough to deploy with next eclipse.  If not please reopen.

Closing.
